const express=require('express')
const fundingAdditionalInformationRouter=express.Router()
const fundingAdditionalInformationController=require('../controller/fundingAdditionalInformationController')
fundingAdditionalInformationRouter.post('/fundingAdditionalInformation',fundingAdditionalInformationController.postFundingAdditionalInformation)

module.exports =fundingAdditionalInformationRouter